name: Test

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04]
        # os: [macOS-latest, windows-2019, ubuntu-18.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: yarn install
        run: |
          yarn install --frozen-lockfile

      - name: yarn test
        uses: GabrielBB/xvfb-action@v1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          run: |
            yarn lint
            yarn test
            yarn build
            # yarn package-ci
            # yarn lint
            # yarn tsc
            # yarn test
            # yarn build-e2e
            # yarn test-e2e

# Need to re-enable once E2E tests are added
